-- AlterTable
ALTER TABLE "BookBorrowed" ALTER COLUMN "loan_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "date_returned" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "BookBorrowing" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "BookSelling" ALTER COLUMN "created_at" DROP DEFAULT,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Log" ALTER COLUMN "createdAt" SET DEFAULT timezone('Asia/Jakarta', now());

-- AlterTable
ALTER TABLE "Membership" ALTER COLUMN "start_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "buy_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "canceled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "ended_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ;
